spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/purchase_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&createDatabaseIfNotExist=true
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: c2VjcmV0LWtleS1mb3ItYmNzZC1wdXJjaGFzZS1wcm9qZWN0LWdlbmVyYXRlZC1ieS1yYW5kb20=